apiVersion: v1
kind: Service
metadata:
  name: mattermost
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 8065
    targetPort: 8065
    protocol: TCP
    name: http
  selector:
    app: mattermost
    tier: app
